name: Dependencies
description: Install dependencies

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
        gcc-multilib \
        g++-multilib
