name: Build and test nturt_stm32_module

on: [push]
jobs:

  Dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y --no-install-recommends \
        gcc-multilib \
        g++-multilib

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

  Build_and_test_F446:
    runs-on: ubuntu-latest
    needs: Dependencies
    steps:
    - name: Build
      run: |
        cmake -DSTM32FAMILY=F4 -DSTM32TYPE=F446 -B build
        cmake --build build -j$(nproc) --config Debug

    - name: Run tests
      run: |
        cd build/test
        ctest -j$(nproc) --output-on-failure

  Build_and_test_G431:
    runs-on: ubuntu-latest
    needs: Dependencies
    steps:
    - name: Build
      run: |
        cmake -DSTM32FAMILY=G4 -DSTM32TYPE=G431 -B build
        cmake --build build -j$(nproc) --config Debug

    - name: Run tests
      run: |
        cd build/test
        ctest -j$(nproc) --output-on-failure

  Build_and_test_H723:
    runs-on: ubuntu-latest
    needs: Dependencies
    steps:
    - name: Build
      run: |
        cmake -DSTM32FAMILY=H7 -DSTM32TYPE=H723 -B build
        cmake --build build -j$(nproc) --config Debug

    - name: Run tests
      run: |
        cd build/test
        ctest -j$(nproc) --output-on-failure
